# Generated by Django 3.2.9 on 2021-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(max_length=100, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_amount',
            field=models.IntegerField(default=1),
        ),
    ]
